apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-demo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-demo-app
      tier: backend
  template:
    metadata:
      labels:
        app: second-demo-app
        tier: backend
    spec:
      containers:
        - name: second-node-js-demo-app
          image: raminarmanfar/kub-demo-app:2
        # - name: ...
        #   image: ...
